language: node_js
node_js:
  - "14.16.1"
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
git:
  depth: 3
notifications:
  email:
    recipients:
      - quantumursua@gmail.com
    on_success: always
    on_failure: always
branches:
  only:
    - master
script:
  - yarn test
  - yarn build
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  local-dir: .next  
  app: empanadas-web-page
  commit_message: "build: project deployment"
  api_key: $HEROKU_TOKEN
  on: master
after_deploy:
  - echo "Application Deployed!"
