version: '3.2'
services:
  mongo-negrita:
    image: mongo:4.4
    container_name: $MONGO_CONTAINER_NAME
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
